// Generated by scripts/vendor-sounds.mjs from static/sounds/sounds.lock.json. Do not edit.
//
// The vendored files each cue may play, under /sounds/ and without the extension: every one exists
// as .ogg and as .mp3, and the player picks the format the browser can play. Where there are
// several, one is picked at random. An empty list is a cue that stays silent.
import type { Cue } from './soundCues';

export const SOUND_FORMATS = ['ogg', 'mp3'] as const;

export const CUE_FILES: Readonly<Record<Cue, readonly string[]>> = {
	dice_roll: [
		'kenney-casino-audio/dice_throw_1',
		'kenney-casino-audio/dice_throw_2',
		'kenney-casino-audio/dice_throw_3',
	],
	piece_move: [],
	piece_capture: [],
	castle: [],
	promotion: ['kenney-interface-sounds/maximize_006'],
	no_move: ['kenney-interface-sounds/glass_004'],
	game_win: ['kenney-music-jingles/pizzicato_02'],
	game_loss: ['kenney-music-jingles/pizzicato_01'],
	game_draw: ['kenney-music-jingles/pizzicato_03'],
};
