// Shared sound service: one preloaded element per file, so repeated plays don't re-fetch or
// re-decode. Playback is best-effort — browsers block audio until the user's first gesture, so
// every element is also "unlocked" on the first pointer/key interaction (muted play+pause),
// letting later programmatic plays through even when they aren't gesture-triggered (e.g. the
// opponent's roll arriving over the wire).
//
// The cues are Dice Chess TV's (#167): `soundCues.ts` says which step of a game plays which cue,
// `soundFiles.ts` (generated by scripts/vendor-sounds.mjs) which vendored files a cue may play.
// As on the TV, cues share three channels — board, dice and result. A capture and the win it
// causes are heard together because they are on different channels; a new cue on a channel cuts
// the last one short instead of piling sounds up.
//
// Levels. The files keep the levels they have on the TV, where the owner chose them by ear: the
// jingles sit about 12 dB above the dice (-12 against -24 to -30 LUFS). SOUND_VOLUME trims them
// all alike, to where the previous, softly mastered roll sat against the WebAudio chime below.

import { logger } from './utils/logger';
import { preferencesStore } from './preferencesStore.svelte';
import type { Cue } from './soundCues';
import { CUE_FILES, SOUND_FORMATS } from './soundFiles';

/** Playback gain for every cue (~-3 dB). iOS Safari ignores `HTMLMediaElement.volume` (always 1),
 * so the files' own levels are the floor there. */
export const SOUND_VOLUME = 0.7;

type Channel = 'board' | 'dice' | 'result';

const CHANNEL: Readonly<Record<Cue, Channel>> = {
	piece_move: 'board',
	piece_capture: 'board',
	castle: 'board',
	promotion: 'board',
	dice_roll: 'dice',
	// Not on the dice channel, where it would cut short the clatter it follows. A roll that ends the
	// game is heard as the result instead.
	no_move: 'result',
	game_win: 'result',
	game_loss: 'result',
	game_draw: 'result',
};

const MIME: Readonly<Record<(typeof SOUND_FORMATS)[number], string>> = {
	ogg: 'audio/ogg; codecs="vorbis"',
	mp3: 'audio/mpeg',
};

const elements = new Map<string, HTMLAudioElement>();
const playing = new Map<Channel, HTMLAudioElement>();
// The take each cue played last. Takes play in turn rather than at random, so the same one never
// plays twice running, which a random draw from three does a third of the time.
const lastTake = new Map<Cue, number>();
// Elements created since the last gesture, waiting for the next one to unlock them.
const locked = new Set<HTMLAudioElement>();
let extension: string | null = null;

function hasAudio(): boolean {
	return typeof window !== 'undefined' && typeof Audio !== 'undefined';
}

/** The first vendored format this browser can play — OGG, the upstream original, where it can;
 * MP3 everywhere else. */
function fileExtension(): string {
	if (extension === null) {
		const probe = new Audio();
		extension = SOUND_FORMATS.find((format) => probe.canPlayType(MIME[format]) !== '') ?? 'mp3';
	}
	return extension;
}

function ensureElement(file: string): HTMLAudioElement {
	let audio = elements.get(file);
	if (!audio) {
		audio = new Audio(`/sounds/${file}.${fileExtension()}`);
		audio.preload = 'auto';
		audio.volume = SOUND_VOLUME;
		elements.set(file, audio);
		lockUntilGesture(audio);
	}
	return audio;
}

function lockUntilGesture(audio: HTMLAudioElement): void {
	if (locked.size === 0) {
		window.addEventListener('pointerdown', unlockAll);
		window.addEventListener('keydown', unlockAll);
	}
	locked.add(audio);
}

function unlockAll(): void {
	window.removeEventListener('pointerdown', unlockAll);
	window.removeEventListener('keydown', unlockAll);
	const waiting = [...locked];
	locked.clear();
	for (const audio of waiting) unlock(audio);
}

/** A muted play+pause on a user gesture whitelists the element for future programmatic playback
 * under browser autoplay policies. */
function unlock(audio: HTMLAudioElement): void {
	if (!audio.paused) return; // a real play is already in flight — nothing to unlock
	audio.muted = true;
	const attempt = audio.play();
	if (!attempt) {
		audio.muted = false;
		return;
	}
	attempt
		.then(() => {
			// The same gesture may have triggered a real play right after this probe (it unmutes the
			// element) — only wind back the silent probe, never actual playback.
			if (audio.muted) {
				audio.pause();
				audio.currentTime = 0;
			}
		})
		.catch(() => {
			// Still blocked — the next play after a real interaction succeeds anyway.
		})
		.finally(() => {
			audio.muted = false;
		});
}

/** Preload every cue's files (and arm the gesture unlock) ahead of the first one. */
export function preloadSounds(): void {
	if (!hasAudio()) return;
	for (const files of Object.values(CUE_FILES)) for (const file of files) ensureElement(file);
}

/** Play one cue, the next of its takes where it has several. Silent for a cue with no files. */
export function playCue(cue: Cue): void {
	if (!hasAudio() || !preferencesStore.soundEnabled) return;
	const files = CUE_FILES[cue];
	if (files.length === 0) return;
	try {
		const take = ((lastTake.get(cue) ?? -1) + 1) % files.length;
		lastTake.set(cue, take);
		const audio = ensureElement(files[take]);
		const channel = CHANNEL[cue];
		const previous = playing.get(channel);
		if (previous && previous !== audio) previous.pause();
		playing.set(channel, audio);
		// The gesture carrying this cue may have just fired the muted unlock probe.
		audio.muted = false;
		audio.currentTime = 0;
		const attempt = audio.play();
		if (attempt) {
			attempt.catch(() => {
				// Autoplay blocked before the first user gesture — drop this one silently.
			});
		}
	} catch (e) {
		logger.error(`Failed to play the ${cue} sound`, e as Error);
	}
}

/** Soft notification chime when receiving a draw offer. */
export function playDrawOfferSound(): void {
	if (!hasAudio() || !preferencesStore.soundEnabled) return;
	try {
		const AudioCtx =
			window.AudioContext ||
			(window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext;
		if (!AudioCtx) return;
		const ctx = new AudioCtx();
		const now = ctx.currentTime;

		const osc1 = ctx.createOscillator();
		const osc2 = ctx.createOscillator();
		const gain = ctx.createGain();

		osc1.type = 'sine';
		osc1.frequency.setValueAtTime(523.25, now); // C5
		osc1.frequency.exponentialRampToValueAtTime(659.25, now + 0.15); // E5

		osc2.type = 'sine';
		osc2.frequency.setValueAtTime(659.25, now + 0.15); // E5
		osc2.frequency.exponentialRampToValueAtTime(783.99, now + 0.3); // G5

		gain.gain.setValueAtTime(0.08, now);
		gain.gain.exponentialRampToValueAtTime(0.001, now + 0.45);

		osc1.connect(gain);
		osc2.connect(gain);
		gain.connect(ctx.destination);

		osc1.start(now);
		osc1.stop(now + 0.15);
		osc2.start(now + 0.15);
		osc2.stop(now + 0.45);

		setTimeout(() => {
			ctx.close().catch(() => {});
		}, 500);
	} catch (e) {
		logger.error('Failed to play draw offer notification sound', e as Error);
	}
}
