# ==============================================================================
# SonarCloud Automatic Analysis Configuration
# ==============================================================================

sonar.sources=src
sonar.tests=src,e2e,scripts
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,e2e/**,scripts/**
sonar.exclusions=scripts/**
