// Pages Function scoped to /_app/* (SvelteKit's hashed build output) by its file-based
// route. The actual "is this really missing" logic is in src/lib/appAssetFallback.ts,
// tested there; this file is the thin Cloudflare-runtime wire (#220, #223).
//
// No @cloudflare/workers-types dependency: this directory is outside tsconfig.json's
// include (generated by svelte-kit sync, scoped to src/), so it is never type-checked by
// `mise run check` either way — a local shape for the one call this makes is enough, and
// keeps the main app's dependency graph untouched for one small edge file.
import { honestAppAssetResponse } from '../../src/lib/appAssetFallback';

interface AssetsFetcher {
	fetch(request: Request): Promise<Response>;
}

export const onRequest = async (context: {
	request: Request;
	env: { ASSETS: AssetsFetcher };
}): Promise<Response> => {
	const response = await context.env.ASSETS.fetch(context.request);
	return honestAppAssetResponse(response);
};
